(function () {
  const scenarioName = "Test_Event";
  if (EightDigits.sf.prototype.hasOwnProperty(scenarioName)) {
    return false;
  }
  EightDigits.sf.prototype[scenarioName] = function () {
    let config = {
      scenarioname: scenarioName,
      analytics: scenarioName,
      controlgroup: 0,
      image: "//cdn.8digits.com/log/r/5aebda0c-0594-4f2e-8a8f-19e4b700b621.jpeg"
    };
    let main = {
      factory: function () {
        return true;
      },
    };
    main.factory.prototype = {
      random: function () {
        let randomVal = 0;
        let randomControlRatio =
          config.controlgroup > 50 ? config.controlgroup : 100 - config.controlgroup;
        if (EightDigits.utils.getCookie("_ed_" + config.scenarioname) == null) {
          randomVal = Math.floor(Math.random() * 10000 + 1);
          EightDigits.utils.setCookie("_ed_" + config.scenarioname, randomVal);
        } else {
          randomVal = parseInt(EightDigits.utils.getCookie("_ed_" + config.scenarioname));
        }
        if (randomVal <= 100 * randomControlRatio) {
          return true;
        } else {
          return false;
        }
      },
      fireEvent: function (eventName, withCookie) {
        const device = window.innerWidth <= 420 ? "mobile" : window.innerWidth <= 768 ? "tablet" : "desktop";
        if (withCookie === true) {
          if (!EightDigits.utils.getCookie(`ed-${config.analytics}${eventName}_${device}`)) {
            EightDigits.analytics.sendEvent(config.analytics, `${eventName}_${device}`);
            EightDigits.utils.setCookie(`ed-${config.analytics}${eventName}_${device}`, "on");
          }
        } else {
          EightDigits.analytics.sendEvent(config.analytics, `${eventName}_${device}`);
        }
      },
      style: function () {
        let css = `
        <style>
          .smpl-${config.scenarioname} img {
            margin-top:20px;
            height:34px;
            width:187px;
          }
          
          @media only screen and (max-width: 576px) {
            .smpl-${config.scenarioname} img {
              margin-top:-44px;
              height:34px; 
              width:187px; 
              left:10px; 
              position:absolute;
            }
          }
        </style>
        `;
        jQuery("head").append(css);
      },
      start: function () {

        const hotelList = [
          "Aska Side Grand Prestige",
          "Acapulco Resort & Convention & Spa",
          "Acropol Of Bodrum Beach Hotel",
          "Acroter Hotel & SPA",
          "Adalya Art Side Hotel",
          "Adalya Elite Lara Hotel",
          "Adalya Ocean Deluxe",
          "Adalya Resort Spa Hotel",
          "Adam & Eve",
          "Adenya Resort Hotels & Spa",
          "Adora Calma Beach Hotel",
          "Adrasan Klados Hotel",
          "Adrasan La Casita Hotel",
          "Alaçatı Alanur Hotel",
          "Alaçatı Marina Palace Butik Otel",
          "Alaroof Butik Otel",
          "Alba Queen Hotel",
          "Alba Resort Hotel",
          "Alba Royal Hotel",
          "Alkan Hotel",
          "Altın Yunus Resort & Thermal Hotel",
          "Altınkum Park Hotel",
          "Amon Hotels Belek",
          "Anjeliq Downtown Hotel",
          "Anjeliq House Hotel",
          "Annabella Diamond Hotel & Spa",
          "Annabella Park Hotel",
          "Aqua Fantasy Aquapark Hotel & Spa",
          "Aquaworld Belek",
          "Arnor De Luxe Hotel & Spa",
          "Asel Hotel Didim",
          "Aska Just In Beach",
          "Aska Lara Resort & Spa",
          "Aslan City Otel",
          "Aslan Corner Otel",
          "Assos Behram Hotel",
          "Assos Dove Hotel Resort & Spa",
          "Assos Eden Beach Hotel",
          "Assos Eden Gardens Hotel",
          "Assos Park Hotel",
          "Atrium Otel",
          "Aurasia Beach Hotel",
          "Aurasia City Hotel",
          "Aydeniz Apart Otel",
          "Aydeniz Otel",
          "Ayvalık Palas Hotel",
          "Ayvalık Sea Resort",
          "Azka Otel & Spa",
          "Azure By Yelken",
          "Babaylon Hotel",
          "BC Spa Hotel",
          "Begonville Beach Hotel",
          "Begonville Hotel",
          "Belconti Resort Hotel",
          "Beldibi Beach Hotel",
          "Belek Soho Beach Club",
          "Bieno Club Sunset Otel & Spa",
          "Bieno Venüs Otel & Spa",
          "Blue Bay Beach Hotel",
          "Blue Dreams Resort",
          "Blue Marlin Deluxe Spa & Resort",
          "Blue Waters Club",
          "Bodrium Otel & Spa",
          "Bodrum Holiday Resort & Spa",
          "Bonjo Club Resort",
          "Boyalık Beach Hotel & SPA",
          "Bumerang Suites Hotel",
          "Butikhan Beach & Deluxe",
          "Calido Maris Hotel",
          "Can Garden Beach",
          "Cape Krio Boutique Hotel & Spa",
          "Champion Holiday Village",
          "Cihantürk Hotel",
          "Class Beach Otel",
          "Club Barbarossa",
          "Club Çapa Hotel",
          "Club Hotel Anjeliq",
          "Club Hotel Falcon",
          "Club Hotel Letoonia Fethiye",
          "Club Hotel Sera",
          "Club Hotel Turan Prince World",
          "Club Marco Polo",
          "Club Marma Hotel",
          "Club Marvy",
          "Club Mega Saray",
          "Club Throne Beach",
          "Concorde Luxury Resort Casino Convention & SPA",
          "Corendon Playa Kemer",
          "Cornelia De Luxe Resort",
          "Cornelia Diamond Golf Resort & Spa",
          "Costa Bodrum City",
          "Costa Farilya Special Class Hotel",
          "Crystal Admiral Resort Suites & Spa",
          "Crystal Aura Beach Resort & Spa",
          "Crystal Deluxe Resort & Spa",
          "Crystal Flora Beach Resort",
          "Crystal Green Bay Resort & Spa",
          "Crystal Palace Luxury Resort & Spa",
          "Crystal Sunrise Queen Luxury Resort & Spa",
          "Crystal Sunset Luxury Resort & Spa",
          "Crystal Tat Beach Golf Resort & Spa",
          "Crystal Waterworld Resort & Spa",
          "Cunda Esen Hotel",
          "Cunda Fora Hotel",
          "Cunda Kıvrak Otel",
          "Cunda Oteli",
          "Cunda Poseidon Otel",
          "Çenger Beach Resort & Spa Hotel",
          "Çıralı Marina Loft",
          "Dalya Resort Hotel",
          "Dalyan Arda Villas",
          "Dalyan Live Spa Resort Hotel",
          "Dalyan Resort Hotel",
          "Dalyan Resort Spa Hotel",
          "Daphnis Hotel",
          "Datça Suites Butik Otel",
          "Deniz Kızı Hotel",
          "Deniz Kızı Royal",
          "Design Plus Seya Beach Hotel",
          "Diamond Beach Hotel & Spa",
          "Diamond De Luxe Hotel & Spa",
          "Diamond Hill Resort Hotel",
          "Diamond Of Bodrum Hotel",
          "Dikili Papaya Evleri",
          "Dionisus Hotel",
          "Dome Hotel",
          "Doora Bodrum Hotel",
          "Doramar Resort & Aqua Tatil Köyü",
          "Doria Hotel Bodrum",
          "Dorman Suites Hotel",
          "Double Tree By Hilton Kuşadası",
          "Dream World Resort",
          "Ece Saray Marina Resort",
          "Ege Birlik Boutique",
          "Ekici Hotel",
          "El Mundo Suites",
          "Ela Excellence Resort Belek",
          "Elegance Hotels International",
          "Elementa Boutique Hotel",
          "Elexus Hotel Resort Casino",
          "Elite Hotel Yalıkavak",
          "Elite World Marmaris Otel",
          "EvN Hotel Dalyan",
          "Fame Beach",
          "Fame Residence Göynük",
          "Fame Residence Kemer & SPA Hotel",
          "Fame Residence Lara & SPA Hotel",
          "Faustina Hotel & Spa",
          "Fiska Boutique Hotel Selimiye",
          "Flora Hotel",
          "Foça Kumsal Hotel",
          "Gloria Serenity Resort",
          "Gloria Verde Resort",
          "Golden Age Crystal Bodrum",
          "Golden Age Hotel Yalıkavak",
          "Golden Life Blue Green & Pasham Hotel",
          "Golden Life Heights Deluxe Suit Hotel",
          "Golden Life Resort Hotel Spa",
          "Golden Life Z Exclusive Hotel",
          "Göcek Lykia Resort Hotel",
          "Gönülhan Otel Alaçatı",
          "Granada Luxury Beach",
          "Grand Park Lara",
          "Grand Şeker Hotel",
          "Grand Temizel",
          "Green Boutique Hotel Selimiye",
          "Green Garden Resort Hotel",
          "Green Nature Diamond Otel",
          "Green Nature Resort & Spa",
          "Greenport Hotel Bodrum",
          "Gulet Hotel",
          "Gümüldür Mavi Deniz Otel",
          "Habesos Hotel",
          "Han Deluxe Hotel",
          "Hapimag Sea Garden Resort",
          "Hawaii Hotel",
          "Haydarpasha Palace",
          "Hedef Beach Resort Hotel",
          "Hedef Kleopatra Golden Sun",
          "Hedef Kleopatra Sand Hotel",
          "Hedef Resort & Spa",
          "Hera Hotel",
          "Herodot Beach Hotel",
          "Hillstone Bodrum Hotel & Spa",
          "Hilton Dalaman Sarıgerme Resort & Spa",
          "Honeymoon Beach Hotel",
          "Hotel Berke Ranch",
          "Hotel Green Gold",
          "Hotel Su",
          "Hotel Turan Prince",
          "Huri & Nuri Hotel",
          "Infinity City Hotel",
          "İda Taş Konak",
          "İdaş Club Hotel",
          "İdaş Hotel",
          "İncekum Beach Resort",
          "İnfinity By Yelken Aquapark & Resort",
          "İnnvista Hotels Belek",
          "Justiniano Deluxe Resort",
          "Kairaba Alaçatı Beach Resort",
          "Kalinda Inn Otel",
          "Katre Otel",
          "Kaya Artemis Resort & Casino",
          "Kaya Palazzo Golf Resort",
          "Kaya Palazzo Resort & Casino",
          "Kaya Palazzo Resort & Residences Le Chic Bodrum",
          "Kaya Side",
          "Kemer Park Otel",
          "Kemerlihan Deluxe Hotel",
          "Kerme Ottoman Gökova",
          "Kerme Ottoman Palace",
          "Kimera Lounge Hotel",
          "Kimeros Park Holiday Village",
          "Kirman Arycanda Deluxe",
          "Kirman Belazur Resort & Spa",
          "Kirman Calyptus Resort & Spa",
          "Kirman Leodikya Resort & Spa",
          "Kirman Sidemarin Beach & Spa",
          "Kirman Sidera Luxury & Spa",
          "Kleopatra Ada Beach Hotel",
          "Kleopatra Ada Hotel",
          "Kleopatra Beach Hotel",
          "Kleopatra Ramira Hotel",
          "Kleopatra Royal Palm Hotel",
          "Koala Bungalows",
          "Korsan Ada Hotel",
          "Kuştur Club Holiday Village",
          "La Kumsal Hotel",
          "La Petra Otel",
          "La Quinta by Wyndham Bodrum",
          "La Vista Boutique Hotel & SPA",
          "Labranda Alantur Resort",
          "Labranda Ephesus Princess",
          "Labranda Excelsior Side",
          "Labranda Güllük Princess",
          "Labranda Lebedos Princess Aegean",
          "Labranda Loryma Resort",
          "Labranda Mares Marmaris",
          "Labranda TMT Bodrum Resort",
          "Laren Seaside Hotel & Spa",
          "Larissa Hotel Beldibi",
          "Larissa Sultan’s Beach Hotel",
          "Le Monde Beach Resort & Spa",
          "Les Ambassadeurs Hotel & Casino",
          "Limak Atlantis De Luxe Hotel & Resort",
          "Limak Cyprus Deluxe Hotel",
          "Limak Lara De Luxe Hotel & Resort",
          "Limak Limra Hotel & Resort",
          "Limonade Pansiyon",
          "Liona Hotel",
          "Liona Residence",
          "Liu Resorts",
          "Lord Marina Otel",
          "Lord's Palace Hotel & Spa & Casino",
          "Lujo Bodrum",
          "Maia Luxury Beach Hotel & Spa",
          "Manaspark Deluxe Hotel",
          "Manastır Otel & Suit",
          "Manzara Boutique Hotel",
          "Marbel Hotel By Palm Wings",
          "Mare Garden Otel",
          "Marmaris Bay Resort By Mp Hotels",
          "Megaş Hotel",
          "Melas Lara Hotel",
          "Melas Resort Hotel",
          "Melas Tatil Köyü",
          "Merit Crystal Cove Hotel & Casino",
          "Merit Lefkoşa Hotel & Casino",
          "Merit Park Hotel & Casino",
          "Merit Royal Hotel & Casino & Spa",
          "Merit Royal Premium Hotel Casino & Spa",
          "Mert Seaside Hotel",
          "Mirage Park Resort",
          "Mirage World",
          "Miramar Hotel",
          "Mulka Hotel",
          "My Marin Hotel",
          "Mylome Luxury Hotel & Resort",
          "Narcia Resort Side",
          "Nashira Resort Hotel & Aqua Spa",
          "Nevada Hotel & Spa",
          "Nirvana Cosmopolitan",
          "Notion Kesre Beach Hotel & Spa",
          "Nova Beach Hotel",
          "Nova Park Hotel",
          "Nuh'un Gemisi Deluxe Hotel & Spa",
          "Orange County Alanya",
          "Orange County Belek",
          "Orange County Kemer – Adult Only +16",
          "Orcey Hotel",
          "Otium Family Eco Club",
          "Otium Park Club Akman",
          "Ören Konak Otel",
          "Örsmaris Boutique Hotel",
          "Özlem Garden Hotel",
          "Palm Wings Beach Resort & Spa Kuşadası",
          "Palm Wings Ephesus Beach Resort",
          "Paloma Finesse",
          "Park Aqua Rooms Otel",
          "Pavel'in Yeri Butik Otel",
          "Petrino Gökçeada Hotel & Kitchen",
          "Pırıl Hotel Thermal & Beauty Spa",
          "Pine Beach Belek",
          "Pine Club Boutique Hotel & Spa",
          "Pirate's Beach Club",
          "Porto Bello Hotel Resort & Spa",
          "Premier Nergis Beach Hotel",
          "Queen's Park Göynük",
          "Queen's Park Le Jardin Resort & Spa",
          "Radisson Blu Resort & Spa Çeşme",
          "Ramada Resort Bodrum",
          "Ramira City Hotel",
          "Ramira Joy Hotel",
          "Rhapsody Hotel Kaş",
          "Rixos Downtown Antalya",
          "Robinson Çamyuva",
          "Robinson Nobilis",
          "Robinson Pamfilya",
          "Robinson Sarıgerme Park",
          "Royal Alhambra Palace Hotel",
          "Royal Asarlık Beach Hotel & Spa",
          "Royal Dragon Hotel",
          "Royal Holiday Palace Hotel",
          "Royal Seginus Hotel",
          "Royal Taj Mahal Hotel",
          "Royal Wings Hotel",
          "Rubi Hotel",
          "Rubi Platinum Sign",
          "Rubi Platinum Spa Resort & Suites",
          "Safir Hotel Bodrum",
          "Sahil Martı",
          "Salamis Bay Conti Resort & Hotel",
          "Salbakos Herakleia Boutique Hotel",
          "Salmakis Otel Bodrum",
          "Samira Resort",
          "Saphir Resort & Spa",
          "Saylam Suites Kaş",
          "Sea Bird Hotel",
          "Seagull Hotel",
          "Seher Resort & Spa",
          "Seher Sun Palace Resort & Spa",
          "Sentido Trendy Verbena Beach",
          "Sertil Royal Forest Hotel",
          "Sesin Hotel Marmaris",
          "Seven Seas Hotel Blue",
          "Seven Seas Hotel Life",
          "Side Kum Hotel",
          "Side Premium",
          "Side Star Beach",
          "Side Star Park",
          "Side Sun Hotel",
          "Side Sunport Hotel & Spa (ex.Side Sungate)",
          "Silver Hotel",
          "Siz İnn Otel Urla",
          "Son Vapur Butik Otel",
          "Sonnen Hotel",
          "Star Hotel Fethiye",
          "Starlight Resort Hotel",
          "Sueno Hotels Beach",
          "Sueno Hotels Deluxe Belek",
          "Sueno Hotels Golf Belek",
          "Sultan of Dreams Hotel & Spa",
          "Sultan Of Side Hotel",
          "Sun Beach Hotel",
          "Sun Beach Park Hotel",
          "Sun Star Beach Hotel",
          "Sun Star Resort Hotel",
          "Sundia By Liberty Ölüdeniz",
          "Sunrise Resort Hotel",
          "Susesi Luxury Resort",
          "Süral Garden Hotel",
          "Süral Hotel",
          "Süral Resort Hotel",
          "Süral Saray Hotel",
          "Swandor Hotels & Resort Topkapı Palace",
          "Taşdelen Alaçatı",
          "Teddy Alaçatı",
          "Telmessos Select Hotel",
          "Temple Miletos & Spa Hotel",
          "Terrace Beach Resort",
          "Terrace Elite Resort",
          "The Bay Beach Club",
          "The Best Life Hotel Bodrum Center",
          "The Colony Hotel",
          "The Corner Park Hotel",
          "The Land of Legends Kingdom Otel",
          "The Lumos Deluxe",
          "The Marilis Hill Resort Hotel & Spa",
          "The Marmara Antalya",
          "The Marmara Bodrum",
          "The Sansa Hotel & Spa",
          "Throne Beach Resort & Spa",
          "Trendy Aspendos Beach",
          "Trendy Palm Beach",
          "Trendy Side Beach Hotels",
          "True Blue Boutique Hotel",
          "Tui Blue Ephesus",
          "Turay Hotel",
          "Türkbükü Hill Hotel",
          "Urla Pier Hotel",
          "Utopia Beach Club",
          "Venezia Palace Deluxe Resort",
          "Venosa Beach Resort Spa",
          "Viento Hotel Alaçatı",
          "Villa Anfora Datça Hotel",
          "Villa Side Hotel",
          "Villa Side Residence",
          "Vita Bella Resort Hotel & Spa",
          "VONRESORT Golden Coast Hotel",
          "Xanadu Island",
          "Xanadu Resort Hotel",
          "Yalı Apart Bodrum",
          "Yalıhan Aspendos Hotel",
          "Yalıhan Una Hotel",
          "Yalıkavak Marina Boutique Hotel",
          "Yalıpark Beach Hotel",
          "Yelken Mandalinci Spa & Wellness Hotel",
          "Zephyros Hotel",
          "Zeynep Hotel",
          "Zeytin Arası Apart Otel",
          "Zeytinada Otel"
        ];

        const html = `
          <span class="smpl-${config.scenarioname}">
            <img src="${config.image}">
          </span>`;

        jQuery(".booking-item").map(function () {
          const hotelName = jQuery(this).find("h3:eq(0)").text().trim();
          if (hotelList.indexOf(hotelName) > -1) {
            if (window.innerWidth > 768) {
              jQuery(this).find(".hotellist-item-information").append(html);
            } else {
              jQuery(this).append(html);
            }
            main.factory.prototype.fireEvent("shown_banner", true);
          }
        });
        main.factory.prototype.style();
      },
      control: function () { },
      init: function () {
        if (main.factory.prototype.control() === false) {
          return false;
        }
        let _exec = main.factory.prototype.random();
        if (!_exec) {
          main.factory.prototype.fireEvent("NotShown", true);
          return false;
        }
        main.factory.prototype.start();
      },
    };

    boot = function () {
      return main.factory.prototype.init();
    };
    boot();
  };
  let ed = {};
  ed["_ed_" + scenarioName] = new EightDigits.sf();
  ed["_ed_" + scenarioName][scenarioName]();
})();