var data = [
  {
  dataID: "2482",
  title: "Vatkalı Triko Süveter",
  href: "/vatkali-triko-suveter",
  discount: 30,
},
{
  dataID: "2485",
  title: "Kare Desen Cep Detaylı Hırka",
  href: "/kare-desen-cep-detayli-hirka",
  discount: 40,
},
{
  dataID: "2487",
  title: "Bağlamalı Saten Bluz",
  href: "/baglamali-saten-bluz",
  discount: 30,
},
{
  dataID: "2486",
  title: "V Yaka Fitilli Triko Hırka",
  href: "/v-yaka-fitilli-triko-hirka",
  discount: 30,
},
{
  dataID: "2500",
  title: "Yanları Büzgülü Crop Body",
  href: "/yanlari-buzgulu-crop-body",
  discount: 30,
},
{
  dataID: "2490",
  title: "Duble Kollu Triko Hırka",
  href: "/duble-kollu-triko-hirka",
  discount: 30,
},
{
  dataID: "2501",
  title: "Denim Kol Sweatshirt",
  href: "/denim-kol-sweatshirt",
  discount: 30,
},
{
  dataID: "2518",
  title: "Cindy Crop Sweatshirt",
  href: "/cindy-crop-sweatshirt",
  discount: 30,
},
{
  dataID: "2538",
  title: "Püskül Detaylı Tüvit Gömlek",
  href: "/puskul-detayli-tuvit-gomlek",
  discount: 30,
},
{
  dataID: "2556",
  title: "Positive View Baskılı Oversize Sweatshirt",
  href: "/positive-view-baskili-oversize-sweatshirt1",
  discount: 40,
},
{
  dataID: "2546",
  title: "Balıkçı Yaka Ribanalı Örgü Kazak",
  href: "/balikci-yaka-ribanali-orgu-kazak",
  discount: 40,
},
{
  dataID: "2584",
  title: "Düşük Omuz Balon Kol Hırka",
  href: "/dusuk-omuz-balon-kol-hirka",
  discount: 40,
},
{
  dataID: "2583",
  title: "Kuzu Desenli Triko Kazak",
  href: "/kuzu-desenli-triko-kazak",
  discount: 60,
},
{
  dataID: "2579",
  title: "Balıksırtı Örgülü Triko Süveter",
  href: "/baliksirti-orgulu-triko-suveter",
  discount: 40,
},
{
  dataID: "2577",
  title: "Zikzak Çizgili Süveter",
  href: "/zikzak-cizgili-suveter",
  discount: 40,
},
{
  dataID: "2574",
  title: "Kruvaze Çift Sıra Düğmeli Triko Hırka",
  href: "/kruvaze-cift-sira-dugmeli-triko-hirka",
  discount: 40,
},
{
  dataID: "2690",
  title: "Çıtçıt Detaylı Kadife Gömlek",
  href: "/citcit-detayli-kadife-gomlek",
  discount: 30,
},
{
  dataID: "2683",
  title: "Leopard Sweatshirt",
  href: "/leopard-sweatshirt",
  discount: 30,
},
{
  dataID: "2718",
  title: "Düz Kesim Salaş Süveter",
  href: "/duz-kesim-salas-suveter",
  discount: 40,
},
{
  dataID: "2757",
  title: "Kuşaklı Balıkçı Yaka Süveter",
  href: "/kusakli-balikci-yaka-suveter",
  discount: 30,
},
{
  dataID: "2746",
  title: "Polo Yaka Kazak",
  href: "/polo-yaka-kazak",
  discount: 40,
},
{
  dataID: "2758",
  title: "Crop Polo Yaka Triko",
  href: "/crop-polo-yaka-triko",
  discount: 30,
},
{
  dataID: "2765",
  title: "Yakası Fitilli Kuşaklı Süveter",
  href: "/yakasi-fitilli-kusakli-suveter",
  discount: 40,
},
{
  dataID: "2781",
  title: "Etnik Desen Triko Yelek",
  href: "/etnik-desen-triko-yelek",
  discount: 40,
},
{
  dataID: "2780",
  title: "Gömlek Kollu Örme Kazak",
  href: "/gomlek-kollu-orme-kazak",
  discount: 40,
},
{
  dataID: "2793",
  title: "Kapüşonlu Örgü Sweat",
  href: "/kapusonlu-orgu-sweat",
  discount: 30,
},
{
  dataID: "2791",
  title: "Etnik Örgü Crop Hırka",
  href: "/etnik-orgu-crop-hirka",
  discount: 30,
},
{
  dataID: "2788",
  title: "Beli Bağcıklı Triko Kazak",
  href: "/beli-bagcikli-triko-kazak",
  discount: 30,
},
{
  dataID: "2783",
  title: "Yumoş Kruvaze Kapamalı Kazak",
  href: "/yumos-kruvaze-kapamali-kazak",
  discount: 30,
},
{
  dataID: "2803",
  title: "Visconsin Baskılı Sweatshirt",
  href: "/visconsin-baskili-sweatshirt",
  discount: 40,
},
{
  dataID: "2799",
  title: "Dekolteli Crop Triko Kazak",
  href: "/dekolteli-crop-triko-kazak",
  discount: 30,
},
{
  dataID: "2802",
  title: "Texas Baskılı Kolej Sweatshirt",
  href: "/texas-baskili-kolej-sweatshirt-2802",
  discount: 30,
},
{
  dataID: "2797",
  title: "Kol Düğmeli Fitilli Bluz",
  href: "/kol-dugmeli-fitilli-bluz-2797",
  discount: 30,
},
{
  dataID: "2844",
  title: "Reglan Kol Dik Yaka Kazak",
  href: "/reglan-kol-dik-yaka-kazak-2844",
  discount: 40,
},
{
  dataID: "2840",
  title: "Vintage Hırka",
  href: "/vintage-hirka",
  discount: 30,
},
{
  dataID: "2847",
  title: "Gömlek Garnili Triko Kazak",
  href: "/gomlek-garnili-triko-kazak",
  discount: 40,
},
{
  dataID: "2845",
  title: "Tom Jerry Kazak",
  href: "/tom-jerry-kazak",
  discount: 30,
},
{
  dataID: "2832",
  title: "Örgü Model Triko Yelek",
  href: "/orgu-model-triko-yelek",
  discount: 30,
},
{
  dataID: "2856",
  title: "Yaka Detay Oversize Crop Hırka",
  href: "/yaka-detay-oversize-crop-hirka-2856",
  discount: 30,
},
{
  dataID: "1680",
  title: "Gömlek Model Kemerli Elbise",
  href: "/gomlek-model-kemerli-elbise",
  discount: 40,
},
{
  dataID: "1658",
  title: "Gipeli Kolu Salaş Model Elbise",
  href: "/gipeli-kolu-salas-model-elbise",
  discount: 30,
},
{
  dataID: "1651",
  title: "Beli Lastikli Çiçek Desenli Elbise",
  href: "/beli-lastikli-cicek-desenli-elbise",
  discount: 40,
},
{
  dataID: "1650",
  title: "Boyundan Bağlamalı Sırt Dekolteli Elbise",
  href: "/boyundan-baglamali-sirt-dekolteli-elbise",
  discount: 40,
},
{
  dataID: "1635",
  title: "Arkadan Bağlamalı Çiçek Desenli Elbise",
  href: "/arkadan-baglamali-cicek-desenli-elbise1",
  discount: 30,
},
{
  dataID: "1628",
  title: "Kloş Etekli Elbise",
  href: "/klos-etekli-elbise",
  discount: 30,
},
{
  dataID: "1698",
  title: "Boydan İnce Piliseli Elbise",
  href: "/boydan-ince-piliseli-elbise",
  discount: 30,
},
{
  dataID: "1738",
  title: "Sırt Dekolteli Saten Elbise",
  href: "/sirt-dekolteli-saten-elbise",
  discount: 40,
},
{
  dataID: "1868",
  title: "Balon Kol Denim Elbise",
  href: "/balon-kol-denim-elbise",
  discount: 40,
},
{
  dataID: "2248",
  title: "Kabartmalı Triko Elbise",
  href: "/kabartmali-triko-elbise",
  discount: 30,
},
{
  dataID: "2202",
  title: "Victoria Dantel Elbise",
  href: "/victoria-dantel-elbise",
  discount: 40,
},
{
  dataID: "2195",
  title: "Balon Kol Deri Elbise",
  href: "/balon-kol-deri-elbise",
  discount: 40,
},
{
  dataID: "2188",
  title: "İp Askılı Büzgülü Elbise",
  href: "/ip-askili-buzgulu-elbise-2188",
  discount: 40,
},
{
  dataID: "2499",
  title: "Askılı Mini Triko Elbise",
  href: "/askili-mini-triko-elbise",
  discount: 30,
},
{
  dataID: "2466",
  title: "Tek Omuz Kruvaze Elbise",
  href: "/tek-omuz-kruvaze-elbise",
  discount: 40,
},
{
  dataID: "2465",
  title: "Düğme Detay Fitilli Mini Elbise",
  href: "/dugme-detay-fitilli-mini-elbise",
  discount: 40,
},
{
  dataID: "2453",
  title: "Baret Dikişli Sweat Elbise",
  href: "/baret-dikisli-sweat-elbise",
  discount: 40,
},
{
  dataID: "2408",
  title: "Omzu Vatkalı Fitilli Triko Elbise",
  href: "/omzu-vatkali-fitilli-triko-elbise",
  discount: 40,
},
{
  dataID: "2407",
  title: "Çizgili Triko Elbise",
  href: "/cizgili-triko-elbise",
  discount: 30,
},
{
  dataID: "2726",
  title: "Dik Yaka Triko Elbise",
  href: "/dik-yaka-triko-elbise1",
  discount: 30,
},
{
  dataID: "2640",
  title: "Kare Yaka Tüvit Elbise",
  href: "/kare-yaka-tuvit-elbise",
  discount: 40,
},
{
  dataID: "2586",
  title: "Pencere Yaka Büzgülü Elbise",
  href: "/pencere-yaka-buzgulu-elbise",
  discount: 40,
},
]