(function () {
    if (EightDigits.sf.prototype.hasOwnProperty("otelTourismSertifikaListingM")) {
        return false
    }
    EightDigits.sf.prototype.otelTourismSertifikaListingM = function () {

        var config = {
            scenarioname: "otelTourismSertifikaListingM",
            analytics: "otelTourismSertifikaListingM",
            controlgroup: 0
        };

        var main = {
            "factory": function () {
                return true;
            }
        };
        main.factory.prototype = {
            random: function () {
                var randomVal = 0;
                var randomControlRatio = config.controlgroup > 50 ? config.controlgroup : 100 - config.controlgroup;
                if (EightDigits.utils.getCookie('_ed_' + config.scenarioname) == null) {
                    randomVal = Math.floor((Math.random() * 10000) + 1);
                    EightDigits.utils.setCookie('_ed_' + config.scenarioname, randomVal);
                } else {
                    randomVal = parseInt(EightDigits.utils.getCookie('_ed_' + config.scenarioname));
                }
                if (randomVal <= 100 * randomControlRatio) {
                    return true;
                } else {
                    return false;
                }
            },
            start: function () {
                var CoronaList =
                    ["1774 Kazdağı Termal Butik Otel",
                    "Abacı Konak Hotel",
                    "Abana Berrunil Otel",
                    "Abant Palace",
                    "Abaylar Otel",
                    "AC Hotel İstanbul By Marriott",
                    "Acer Cave Hotel",
                    "Acropol Of Bodrum Beach Hotel",
                    "Acroter Hotel & SPA",
                    "Adalya Elite Lara Hotel",
                    "Adalya Ocean Deluxe",
                    "Adalya Resort Spa Hotel",
                    "Adam & Eve",
                    "Adana HiltonSA",
                    "Adana Otel Şenbayrak City",
                    "Adana Plaza Otel",
                    "Adempira Termal & Spa Hotel",
                    "Aden Hotel Cappadocia",
                    "Adenya Resort Hotels & Spa",
                    "Adin Beach Hotel",
                    "Adramis Termal Hotel",
                    "Adranos Hotel",
                    "Adresin Hotel Edirne",
                    "Adrina Termal Health&Spa Hotel",
                    "Ag Hotels Antalya",
                    "Agiros Termal Hotel",
                    "Agrigento Resort Hotel",
                    "Ağaçlı Turistik Tesisleri Otel",
                    "Ağaoğlu My City Hotel",
                    "Ağaoğlu My Mountain",
                    "Ak Life Hotel Suit",
                    "Akar International Hotel",
                    "Akay Garden Family Club",
                    "Akbulut Hotel & Spa",
                    "Akgün Hotel Elazığ",
                    "Akgün Hotel İstanbul",
                    "Akkan Beach Hotel",
                    "Akkan Beach Hotel",
                    "Akkan Luxury Hotel Bodrum",
                    "Akkan Otel",
                    "Akkoç Butik Hotel",
                    "Akol Hotel",
                    "Akra Hotel",
                    "Akra V",
                    "Akrones Thermal Spa Convention Sport Hotel",
                    "Aksaç Otel",
                    "Aksular Otel",
                    "Aktaş Otel",
                    "Aktur Residence",
                    "Alaçatı Kapari Otel",
                    "Alaiye Resort & Spa Hotel",
                    "Alasonya Otel Alaçatı by Lamira",
                    "Alba Ankara Hotel",
                    "Alba Queen Hotel",
                    "Albena Club Hotel",
                    "Aldino Otel",
                    "Alesta Yacht Hotel",
                    "Alfin Hotel",
                    "Alkan Hotel",
                    "Allium Villas Resort",
                    "Almira Hotel Thermal Spa & Convention Center",
                    "Alp Paşa Hotel",
                    "Altın Yunus Apart",
                    "Altın Yunus Resort & Thermal Hotel",
                    "Altınorfoz Hotel",
                    "Altınöz Hotel",
                    "Amazon Aretias Hotel",
                    "Ambrosia Hotel",
                    "Amossia Elite Hotel",
                    "Anadolu Hotels Downtown Ankara",
                    "Anatolia Boutique Otel",
                    "Anatolia Hotel Bursa",
                    "Anatolian Houses",
                    "Ancere Thermal Hotel",
                    "Anemon Ankara Oteli",
                    "Anemon Antakya",
                    "Anemon Çiğli Otel",
                    "Anemon Denizli Otel",
                    "Anemon Diyarbakır",
                    "Anemon Ege Sağlık",
                    "Anemon Eskişehir",
                    "Anemon İskenderun",
                    "Anemon İzmir",
                    "Anemon Konya Hotel",
                    "Anemon Malatya",
                    "Anemon Manisa Otel",
                    "Anemon Ordu",
                    "Anemon Samsun Otel",
                    "Angel's Marmaris Hotel",
                    "Angel's Park Hotel",
                    "Anitta Hotel",
                    "Ankara HiltonSA",
                    "Ankara Plaza Hotel",
                    "Annabella Diamond Hotel & Spa",
                    "Antakya Ottoman Palace Thermal Resort & Spa",
                    "Antalya Hotel Resort & Spa",
                    "Antiochos Hotel",
                    "Antique Roman Palace",
                    "Antmare Alaçatı Hotel",
                    "Apple Palace Hotel",
                    "Aqua Fantasy Aquapark Hotel & Spa",
                    "Aquaworld Belek By Mp Hotels",
                    "Argos in Cappadocia",
                    "Ariana Sustainable Luxury Lodge",
                    "Arinnanda Otel",
                    "Aripsas Hotel",
                    "Armada Hotel",
                    "Armas Termal Resort Kırşehir",
                    "Armina Termal Hotel",
                    "Armina Termal Hotel",
                    "Armis Hotel",
                    "Armoni Park Otel Kastamonu",
                    "Arnor De Luxe Hotel & Spa",
                    "Arora Hotel",
                    "Artemis Princess Hotel",
                    "Artıç Hotel",
                    "Arts Hotel İstanbul",
                    "Arus Otel",
                    "Aselia Hotel Trabzon",
                    "Asena Hotel",
                    "Aska Just In Beach",
                    "Aska Lara Resort & Spa",
                    "Aska Side Grand Prestige",
                    "Aslı Boutique Otel",
                    "Asrın Beach Hotel",
                    "Asrın Park Hotel & Spa",
                    "Assos Barbarossa Hotel",
                    "Assos Behram Hotel",
                    "Assos Dove Hotel Resort & Spa",
                    "Assos Eden Beach Hotel",
                    "Assos Eden Gardens Hotel",
                    "Assos Hunters Hotel",
                    "Assos Kartal Yuvası Hotel",
                    "Assos Kervansaray Hotel",
                    "Assos Nazlıhan Hotel",
                    "Assos Nazlıhan Spa Hotel",
                    "Assos Park Hotel",
                    "Asteria Kremlin Palace",
                    "Asya Hotel Balıkesir",
                    "Asya Otel",
                    "Ataköşk Otel",
                    "Atalay Otel",
                    "Atalla Hotel",
                    "Atamer Turistik Tesisleri",
                    "Ataol Çan Termal Otel",
                    "Atışkan Hotel",
                    "Atlas Hotel",
                    "Atrium Otel",
                    "Aurasia Beach Hotel",
                    "Aurasia Beach Hotel",
                    "Aurasia City Otel",
                    "Aurum Trabzon Hotel & Spa",
                    "Avantgarde Collection Hotel Levent",
                    "Avantgarde Collection Taksim Square",
                    "Avantgarde Yalıkavak",
                    "Avec Hotel",
                    "Avşar Hotel",
                    "Ayder Doğa Resort",
                    "Aydınbey Famous Resort",
                    "Aydınbey Gold Dreams Hotel",
                    "Aydınbey King's Palace & Spa",
                    "Aygür Hotel",
                    "Ayıntap Otel",
                    "Aymira Hotel & Spa",
                    "Aymira Hotel & Spa",
                    "Aytaş Club Hotel",
                    "Azka Otel & Spa",
                    "B Business Hotel & Spa",
                    "Babaylon Hotel",
                    "Babillon Hotel & Spa",
                    "Bacacan Hotel",
                    "Baga Hotel Akyaka +13 Adult Only",
                    "Bağlar Saray Hotel",
                    "Balçova Termal Otel",
                    "Baleze Boutique Hotel",
                    "Balıktaşı City Hotel",
                    "Balta Hotel",
                    "Baltürk Otel Kocaeli",
                    "Bandırma Palas Hotel",
                    "Baraka Hisarönü",
                    "Barbarossa Club Hotel Mersin",
                    "Barden Hotel",
                    "Barida Hotels",
                    "Basmacıoğlu Hotel Isparta",
                    "Başkent Hotel",
                    "Batıhan Beach Resort",
                    "Bayır Diamond Hotel & Convention Center Konya",
                    "Bayramoğlu Resort Hotel",
                    "BB Çelik Palace Bursa",
                    "BC Spa Hotel",
                    "Beceren Otel",
                    "Begonville Beach Hotel",
                    "Begonville Hotel",
                    "Belconti Resort Hotel",
                    "Belek Soho Beach Club",
                    "Belek'te Her Şey Dahil Yaz Fırsatları",
                    "Belkon Hotel",
                    "Bella Resort & Spa",
                    "Bera Alanya Otel",
                    "Bera Hotel Konya",
                    "Berksoy Hotel",
                    "Berraksu Hotel",
                    "Best Hotel Ankara",
                    "Best Western Hotel Konak",
                    "Best Western Otel 2000",
                    "Best Western Plus Center Hotel",
                    "Best Western Plus Çeşme Hotel",
                    "Best Western Plus Khan Hotel",
                    "Best Western Premier Karşıyaka",
                    "Beyond Hotel",
                    "Bezginler Hotel",
                    "Biblos Resort Alaçatı",
                    "Bilem High Class Hotel",
                    "Bilgehan Hotel",
                    "Bilkent Otel ve Konferans Merkezi",
                    "Binkap Resort Otel",
                    "Birun Kümbet Dağ Evi",
                    "Bitez Garden Life Hotel & Suites",
                    "Black Bird Thermal Hotel & Spa",
                    "Blanca Hotel",
                    "Blue Bay Beach Hotel",
                    "Blue Bay Platinum",
                    "Blue Mudanya Hotel",
                    "Blue Valley Cave Hotel",
                    "Blue Waters Club",
                    "Blueberry Boutique Hotel",
                    "BN Hotel Thermal & SPA",
                    "Bodrium Hotel &You SPA",
                    "Bodrum Holiday Resort & Spa",
                    "Bof Hotels Uludağ Ski & Convention Resort",
                    "Bolat Otel",
                    "Bolat Otel",
                    "Bolu Koru Hotels Spa & Convention",
                    "Bolu Termal",
                    "Bosphorus Sorgun Hotel",
                    "Boyalık Beach Hotel & SPA",
                    "Boyugüzel Termal Hotel",
                    "Bozdoğan Hotel",
                    "Bozooğulları Hotel",
                    "Budan Thermal Spa Hotel & Convention Center",
                    "Burgaz İzer Otel",
                    "Burgaz İzer Otel",
                    "Buruciye Otel",
                    "Butikhan Beach & Deluxe",
                    "Büpa Hotel",
                    "Büyük Abant Oteli & Kongre Merkezi",
                    "Büyük Anadolu Ereğli Hotel",
                    "Büyük Bayburt Oteli",
                    "Büyük Çankırı Otel",
                    "Büyük Erzincan Otel",
                    "Büyük Mardin Oteli",
                    "Büyük Mardin Oteli",
                    "Büyük Osmaniye Oteli",
                    "Büyük Saruhan Hotel",
                    "Büyük Truva Oteli",
                    "Büyük Urartu Otel",
                    "Büyük Veliç Hotel",
                    "Büyük Veliç Hotel",
                    "Büyükhanlı Park Hotel & Residence",
                    "BVS Bosphorus Resort Hotel & Spa",
                    "By Cappadocia Hotel & Spa",
                    "ByOtell",
                    "Calista Luxury Resort",
                    "Can Garden Beach",
                    "Cape Bodrum Beach Resort",
                    "Cape Krio Boutique Hotel & Spa",
                    "Capella Otel",
                    "Cappadocia Cave Resort & Spa",
                    "Cappadocia Estates",
                    "Caresse A Luxury Collection Resort & Spa",
                    "Carmine Hotel",
                    "CarpeDiem Diamond Otel",
                    "Cartoon Hotel",
                    "Casa Aria Hotel",
                    "Casa Caria Boutique Hotel",
                    "Casa Sur Antalya",
                    "Casablanca Garden Otel",
                    "Cassiel Hotel Boutique",
                    "Celal Ağa Konağı Hotel",
                    "Celal Sultan Hotel",
                    "Cender Hotel",
                    "Centro Westside Istanbul",
                    "Ceshmeplus Hotel & Beach",
                    "Cettia Beach Resort",
                    "Cevahir Hotel Asia",
                    "Charisma Deluxe",
                    "Cherry Garden City Spa Hotel",
                    "Cihantürk Hotel",
                    "Citrus Park Hotel",
                    "City Center Otel Taksim",
                    "City One Hotel",
                    "Cityloft Hotel Ataşehir",
                    "Cityloft Hotel Ataşehir",
                    "CK Farabi Hotel",
                    "Clarion Hotel Golden Horn",
                    "Clarion Hotel İstanbul Mahmutbey",
                    "Clarion Hotel Kahramanmaraş",
                    "Class Beach Otel",
                    "CLC Kuşadası Golf & Spa Resort",
                    "Club Alla Turca Hotel",
                    "Club Aqua Plaza",
                    "Club Datça Tatil Köyü",
                    "Club Dedeman Bodrum",
                    "Club Grand Side",
                    "Club Hotel Falcon",
                    "Club Hotel Letoonia Fethiye",
                    "Club Hotel Meri",
                    "Club Hotel Sera",
                    "Club Hotel Sidar",
                    "Club Hotel Turan Prince World",
                    "Club Marco Polo",
                    "Club Marma Hotel",
                    "Club Marvy",
                    "Club Med Palmiye",
                    "Club Mermaid Village",
                    "Club Resort Atlantis",
                    "Club Rose Bay Hotel",
                    "Club Scala Nuova",
                    "Club Turtaş Beach Hotel",
                    "Comet Deluxe Hotel",
                    "Concorde De Luxe Resort",
                    "Conrad İstanbul Bosphorus",
                    "Cornelia De Luxe Resort",
                    "Cornelia Diamond Golf Resort & Spa",
                    "Costa Bodrum City",
                    "Costa Farilya Special Class Hotel",
                    "Costa Maya Bodrum",
                    "Courtyard by Marriott İstanbul İnternational Airport",
                    "CP Ankara Hotel",
                    "Crowne Plaza Cappadocia Nevşehir",
                    "Crowne Plaza İstanbul Asia",
                    "Crowne Plaza İstanbul Florya",
                    "Crowne Plaza Oryapark",
                    "Crystal Admiral Resort Suites & Spa",
                    "Crystal Deluxe Resort & Spa",
                    "Crystal Family Resort & Spa",
                    "Crystal Flora Beach Resort",
                    "Crystal Green Bay Resort & Spa",
                    "Crystal Palace Luxury Resort & Spa",
                    "Crystal Waterworld Resort & Spa",
                    "Cuci Hotel",
                    "Cunda Fora Glamping",
                    "Cunda Fora Hotel",
                    "Cunda Oteli",
                    "Cunda Rota Garden Otel",
                    "Cunda Rota Seaside Otel",
                    "Cura Hotel",
                    "CVK Hotels & Resort Park Bosphorus İstanbul",
                    "Çakmak Marble Hotel",
                    "Çam Thermal Resort & Spa Convention Center",
                    "Çamkar Otel",
                    "Çanak Hotel",
                    "Çankırı Koç Otel",
                    "Çavuşoğlu Tower Hotel",
                    "Çenger Beach Resort & Spa Hotel",
                    "Çerkezköy Business Hotel",
                    "Çerkezköy Hotel Pasha",
                    "Çetin Prestige Resort",
                    "Çetinel Tesisleri Hotel",
                    "Çınar Otel",
                    "Çınar Otel",
                    "Çırağan Palace Hotel Kempinski",
                    "Çimenoğlu Otel",
                    "Çukurova Erten Otel",
                    "Çukurovapark Otel",
                    "D Maris Bay",
                    "D Resort Göcek",
                    "D Resort Murat Reis Ayvalık",
                    "Daisy Garden Resort",
                    "Dalaman Airport Lykia Resort Hotel",
                    "Dalgıçlar Otel",
                    "Dalyan Live Spa Resort Hotel",
                    "Dalyan Resort Hotel",
                    "Datça Otel Mavi Beyaz",
                    "Dedeman Bostancı Hotel & Convention Center",
                    "Dedeman Hotel İstanbul",
                    "Dedeman Konya Convention Center",
                    "Dedeman Palandöken",
                    "Dedeman Palandöken Ski Lodge",
                    "Dedeman Park Elazığ",
                    "Dedeman Park Gaziantep",
                    "Dedeman Şanlıurfa",
                    "Dedeman Tokat",
                    "Dedeman Zonguldak",
                    "Dedepark Hotel",
                    "Delta Hotel By Marriott Bodrum",
                    "Demircioğlu Park Otel",
                    "Demonti Hotel",
                    "Demora Hotel",
                    "Demosan Spa&Otel",
                    "Dere Suites Cappadocia",
                    "Derici Otel",
                    "Des Otel Tekirdağ",
                    "Design Plus Seya Beach Hotel",
                    "Devin Otel",
                    "Diamond De Luxe Hotel & Spa",
                    "Diamond Hill Resort Hotel",
                    "Diamond Of Bodrum Hotel",
                    "Diamond Premium Hotel & Spa Hotel",
                    "Diapolis Hotel",
                    "Didim Beach Elegance",
                    "Dinler Hotel Ürgüp",
                    "Dionisus Hotel",
                    "Divan Adana",
                    "Divan Ankara",
                    "Divan Bodrum",
                    "Divan City Hotel",
                    "Divan Çorlu",
                    "Divan Diyarbakır",
                    "Divan Gaziantep",
                    "Divan İstanbul Asia",
                    "Divan İstanbul Taksim",
                    "Divan Mersin",
                    "Doğa Thermal Health&Spa",
                    "Doğan Hotel By Prana Hotels & Resorts",
                    "Doğramacı Otel",
                    "Doramar Resort & Aqua Tatil Köyü",
                    "Doria Hotel Bodrum",
                    "Dorman Suites Hotel",
                    "Dorukkaya Ski & Mountain Resort",
                    "Double Royal Hotel Darıca",
                    "Double Tree By Hilton Kuşadası",
                    "Double Tree By Hilton Kuşadası",
                    "DoubleTree By Hilton Adana",
                    "DoubleTree By Hilton Afyonkarahisar",
                    "DoubleTree by Hilton Antalya City Centre",
                    "DoubleTree by Hilton Bodrum Işıl Club Resort",
                    "DoubleTree By Hilton Elazığ",
                    "DoubleTree By Hilton Gaziantep",
                    "DoubleTree By Hilton İstanbul Avcılar",
                    "DoubleTree by Hilton İstanbul Esentepe",
                    "DoubleTree By Hilton İstanbul Moda",
                    "DoubleTree by Hilton İstanbul Topkapı",
                    "DoubleTree By Hilton İstanbul Tuzla",
                    "DoubleTree By Hilton İzmir Airport",
                    "DoubleTree By Hilton İzmir Alsancak",
                    "DoubleTree By Hilton Kocaeli",
                    "DoubleTree By Hilton Trabzon",
                    "DoubleTree By Hilton Ümraniye",
                    "DoubleTree by Hilton Van",
                    "Dragut Point South Hotel",
                    "Dream Hill Business Deluxe Hotel",
                    "Dream Time Hotel Antalya",
                    "Dream World Aqua",
                    "Dream World Hill",
                    "Duja Bodrum Otel",
                    "Dündar Hotel",
                    "Ece Saray Marina Resort",
                    "Edi's Premier Hotel",
                    "Efeler Otel",
                    "Ege Palas",
                    "Eken Prestige Hotel",
                    "Eken Resort Hotel",
                    "Ekici Hotel",
                    "Ekin Ata Grand Toprak Hotel",
                    "El Garden Hotel & Residence",
                    "El Ruha Hotel",
                    "Ela Quality Resort Belek",
                    "Elegance East Hotel",
                    "Elegance Hotels International",
                    "Elegance Resort Hotel Yalova",
                    "Elifim Resort Hotel",
                    "Elika Cave Suites",
                    "Elisa Otel",
                    "Elit Asya Hotel",
                    "Elit Palas Special Class Hotel",
                    "Elite Hotel Küçükyalı",
                    "Elite Hotel Yalıkavak",
                    "Elite Luxury Suite Hotel",
                    "Elite World Asia Hotel",
                    "Elite World İstanbul Hotel",
                    "Elite World Marmaris Otel",
                    "Elite World Sapanca Convention&Wellness Resort",
                    "Elite World Van",
                    "Eliz Hotel Convention Center Thermal Spa Wellness",
                    "Ema Öztürk Termal Otel",
                    "Emen's Hotel",
                    "Emet Thermal Resort & Spa",
                    "Emexotel Kocaeli",
                    "Emin Koçak Hotel",
                    "Emin Koçak Hotel",
                    "Emir Royal Hotel",
                    "Emirgan Otel",
                    "Enerji Otel",
                    "Entur Termal Otel",
                    "Eretna Hotel & SPA",
                    "Esila Hotel",
                    "Eskiceshme Bodrum",
                    "Eskişehir Büyük Hotel",
                    "Espina Hotel",
                    "Euro Park Otel",
                    "Exedra Hotel Cappadocia",
                    "ExpoRoyal Hotel",
                    "Extenso Hotel",
                    "Eyüboğlu Hotel",
                    "Fairmont Quasar İstanbul",
                    "Fame Hotel",
                    "Fame Residence Göynük",
                    "Fame Residence Kemer & SPA Hotel",
                    "Fame Residence Lara & SPA Hotel",
                    "Familya Otel",
                    "Faustina Hotel & Spa",
                    "Fayton Hotel",
                    "Fenerbahçe Serkan Acar Resort & Sports Topuk Yaylası",
                    "Ferahi Evler Butik Otel",
                    "Ferko Ilgaz Mountain Hotel & Resort",
                    "Fier Boutique Hotel",
                    "Fimar Life Thermal Resort Hotel",
                    "First Class Hotel",
                    "Flamingo Residence",
                    "Flora Hotel",
                    "Form Hotel Thermal & Spa",
                    "Formback Termal Otel Bursa",
                    "Four Points by Sheraton izmir",
                    "Fourway Hotel",
                    "Fuat Paşa Yalısı",
                    "Galatas Hotel İstanbul",
                    "Gamirasu Cave Hotel",
                    "Garcia Resort & Spa",
                    "Garden Kale Termal Otel",
                    "Gazelle Resort & Spa",
                    "Gherdan Gold Otel",
                    "Gloria Golf Resort",
                    "Gloria Serenity Resort",
                    "Gold 3 Hotel",
                    "Golden Horn Sirkeci Hotel",
                    "Golden Key Kartalkaya",
                    "Golden Life Resort Hotel Spa",
                    "Golden Orange Hotel",
                    "Golden Palas Hotel",
                    "Goldenday Wings Hotel",
                    "Gorrion Hotel İstanbul",
                    "Göcek Lykia Resort Hotel",
                    "Gönen Termal Güneş Otel",
                    "Gönen Termal Park Otel",
                    "Gönen Termal Yıldız Otel",
                    "Gönlüferah City",
                    "Gönlüferah Thermal & Spa Hotel",
                    "Göreme Kaya Otel",
                    "Görükle Oruç Hotel SPA",
                    "Gösterişli Otel",
                    "Granada Luxury Beach",
                    "Grand Akkoza Hotel",
                    "Grand Ali'n Otel Turhal",
                    "Grand Altuntaş Hotel",
                    "Grand Ankara Hotel & Convention Center",
                    "Grand Anzac Otel",
                    "Grand Aras Hotel & Suites",
                    "Grand Artvin Otel",
                    "Grand Astra Resort Hotel",
                    "Grand Asya Hotel",
                    "Grand Ata Park Hotel",
                    "Grand Atakum Hotel",
                    "Grand Belish Resort & Spa",
                    "Grand Beyazıt Hotel",
                    "Grand Boğaziçi Otel",
                    "Grand Boss Suit Hotel",
                    "Grand Cenas Otel",
                    "Grand Cettia Hotel",
                    "Grand Cevahir Hotel Convention Center",
                    "Grand Corner Boutique Hotel",
                    "Grand Çalı Hotel",
                    "Grand Çavuşoğlu Hotel",
                    "Grand Çınar Otel Kütahya",
                    "Grand Çınar Otel Kütahya",
                    "Grand Denizli Hotel",
                    "Grand Emir Hotel & Spa",
                    "Grand Güllük Hotel",
                    "Grand Hasankeyf Otel",
                    "Grand Hilarium Hotel",
                    "Grand Hotel Belekoma",
                    "Grand Hotel Gaziantep",
                    "Grand Hotel Haliç",
                    "Grand Hotel Konya",
                    "Grand Hotel Niğde",
                    "Grand Hotel Ontur Çeşme",
                    "Grand Hotel Silopi",
                    "Grand Hotel Terme",
                    "Grand Hotel Tesk",
                    "Grand Hotel Uzcan",
                    "Grand Hyatt İstanbul",
                    "Grand İsias Hotel",
                    "Grand İskender Hotel",
                    "Grand İtimat Hotel",
                    "Grand Karaman Hotel",
                    "Grand Kartal",
                    "Grand Keskin Hotel",
                    "Grand Makel Hotel",
                    "Grand Merpond",
                    "Grand Millennium Konya",
                    "Grand Miramor Hotel",
                    "Grand Özeren Hotel&SPA",
                    "Grand Öztanık Hotel",
                    "Grand Park Bodrum",
                    "Grand Park Kemer",
                    "Grand Park Lara",
                    "Grand Saatçioğlu Otel",
                    "Grand Ser Hotel",
                    "Grand Simay Hotel",
                    "Grand Sinan Hotel",
                    "Grand Şaroğlu Hotel",
                    "Grand Şeker Hotel",
                    "Grand Temizel",
                    "Grand Urfa Hotel",
                    "Grand Vaves Otel",
                    "Grand Yazıcı Club Marmaris Palace",
                    "Grand Yazıcı Club Turban Thermal Hotel",
                    "Grannos Thermal Hotel & Convention Center",
                    "Gravel Hotels",
                    "Green Nature Diamond Otel",
                    "Green Nature Resort & Spa",
                    "Green Suada Butik Otel",
                    "Greenport Hotel Bodrum",
                    "Grida City Antalya",
                    "Güler Park Hotel",
                    "Güllü Konakları",
                    "Gülümser Hatun Termal",
                    "Güre Termal Resort",
                    "Güvenay Business Hotel",
                    "Habitat Otel Sarıkamış",
                    "Hadrian Butik Otel Erdek",
                    "Hadrianus Hotel",
                    "Hadrianus Hotel",
                    "Haldi Otel",
                    "Hampton By Hilton Bolu",
                    "Hampton By Hilton Bursa",
                    "Hampton By Hilton Çanakkale Gelibolu",
                    "Hampton By Hilton Gaziantep",
                    "Hampton By Hilton İstanbul Ataköy",
                    "Hampton by Hilton İstanbul Kurtköy",
                    "Hampton By Hilton İstanbul Zeytinburnu",
                    "Hampton by Hilton İzmir Aliağa",
                    "Hampton By Hilton Kahramanmaraş",
                    "Hampton By Hilton Ordu",
                    "Hampton By Hilton Samsun",
                    "Hancıoğlu Çamburnu Orman Evleri Bungalow & Hotel",
                    "Hanedan Otel",
                    "Hangover Central Hotel",
                    "Hanzade Park Hotel",
                    "Hapimag Sea Garden Resort",
                    "Happy Hotel",
                    "Harman Hotel",
                    "Harran Otel",
                    "Hattuşa Vacation Club Ankara",
                    "Hattuşa Vacation Club Hatay",
                    "Hattuşa Vacation Club Kazdağları",
                    "Hay Hotel Alsancak",
                    "Haydarpasha Palace",
                    "Hedef Beyt Hotel Resort & Spa",
                    "Hedef Resort & Spa",
                    "Herakles Thermal Otel",
                    "Herodot Beach Hotel",
                    "Hierapark Thermal & Spa Hotel",
                    "Highway Otel",
                    "Hilas Thermal Resort Spa & Aqua",
                    "Hillside Beach Club",
                    "Hillstone Bodrum Hotel & Spa",
                    "Hilly Hotel",
                    "Hilton Bodrum Türkbükü Resort & Spa",
                    "Hilton Bursa Convention Center & Spa",
                    "Hilton Dalaman Sarıgerme Resort & Spa",
                    "Hilton Garden Inn Ankara Gimat",
                    "Hilton Garden Inn Çorlu",
                    "Hilton Garden Inn Diyarbakır",
                    "Hilton Garden Inn Erzincan",
                    "Hilton Garden Inn Eskişehir",
                    "Hilton Garden Inn Isparta",
                    "Hilton Garden Inn İstanbul Beylikdüzü",
                    "Hilton Garden Inn İstanbul Golden Horn",
                    "Hilton Garden Inn İstanbul Ümraniye",
                    "Hilton Garden Inn İzmir Bayraklı",
                    "Hilton Garden Inn Kocaeli Şekerpınar",
                    "Hilton Garden Inn Konya",
                    "Hilton Garden Inn Kütahya",
                    "Hilton Garden Inn Mardin",
                    "Hilton Garden Inn Safranbolu",
                    "Hilton Garden Inn Şanlıurfa",
                    "Hilton Garden Inn Yalova",
                    "Hilton İstanbul Bomonti Hotel & Convention Center",
                    "Hilton İstanbul Bosphorus",
                    "Hilton İstanbul Kozyatağı",
                    "Hilton İstanbul Maslak",
                    "Hilton İzmir",
                    "HM Commerce Hotel",
                    "Holiday Inn Ankara Kavaklıdere",
                    "Holiday Inn Antalya Lara",
                    "Holiday Inn Bursa",
                    "Holiday Inn Bursa City Centre",
                    "Holiday Inn Çukurambar",
                    "Holiday Inn Express Altunizade",
                    "Holiday Inn Gaziantep",
                    "Holiday Inn Gebze İstanbul Asia",
                    "Holiday Inn Istanbul Airport",
                    "Holiday Inn Istanbul Old City",
                    "Holiday Inn İstanbul Kadıköy",
                    "Holiday Inn İstanbul Tuzla Bay",
                    "Holiday Inn Kayseri",
                    "Holiday Inn Şişli",
                    "Hotel Adanava",
                    "Hotel Akyüz",
                    "Hotel Ambrosia",
                    "Hotel Anibal",
                    "Hotel Berke Ranch",
                    "Hotel Billurcu",
                    "Hotel Bosnalı",
                    "Hotel Caeli Eceabat",
                    "Hotel Carina",
                    "Hotel Fuat Van",
                    "Hotel Gold Majesty",
                    "Hotel Golden Way Giyimkent",
                    "Hotel Grand Ereğli",
                    "Hotel Grand Washington",
                    "Hotel Hegsagone Marine Asia",
                    "Hotel İçkale",
                    "Hotel İstanköy",
                    "Hotel Karbel Beach",
                    "Hotel Karia Princess",
                    "Hotel Karia Princess",
                    "Hotel La Bella Alaşehir",
                    "Hotel La Bella Bergama",
                    "Hotel Laville",
                    "Hotel Manas Park Ölüdeniz",
                    "Hotel Manas Park Ölüdeniz",
                    "Hotel Manaspark Ölüdeniz",
                    "Hotel Petek",
                    "Hotel Rena",
                    "Hotel Samara Bodrum",
                    "Hotel Samos",
                    "Hotel Silvanus",
                    "Hotel Star Royal",
                    "Hotel Su",
                    "Hotel Şenler",
                    "Hotel Tatvan Kardelen",
                    "Hotel Torbahan & Beach",
                    "Hotel Turan Prince",
                    "Hotel Turkuaz",
                    "Houston Hotel",
                    "Hyatt Centric Levent Istanbul",
                    "Hyatt Regency İstanbul Ataköy Hotel",
                    "Ic Hotels Green Palace",
                    "IC Hotels Santai Family Resort",
                    "Innvista Hotels Belek",
                    "ISG Airport Hotel",
                    "ISGİnce",
                    "İbis Adana",
                    "İbis Ankara Airport",
                    "İbis Hotel Bursa",
                    "İbis Hotel Eskişehir",
                    "İbis Hotel Gaziantep",
                    "İbis Hotel İstanbul Zeytinburnu",
                    "İbis Hotel Kayseri",
                    "İbis İstanbul Esenyurt",
                    "İbis İstanbul Tuzla",
                    "İbis İstanbul West",
                    "İbis İzmir Alsancak",
                    "İbis Konya",
                    "İbis Style Bomonti",
                    "İbis Style Bornova",
                    "İbis Styles Ataşehir",
                    "İda Costa Hotel",
                    "İda Kale Resort Hotel",
                    "İdahan Hotel",
                    "İdaş Club Hotel",
                    "İdaş Hotel",
                    "İdaş Hotel İçmeler",
                    "İğneada Resort Hotel & Spa",
                    "İkbal Thermal Hotel & Spa",
                    "İlayda Avantgarde Hotel",
                    "İlayda Hotel",
                    "İlci Residence Hotel",
                    "İmperial Turkiz Resort Hotel",
                    "İmren Han Otel",
                    "İnan Kardeşler Bungalow & Motel",
                    "İncekum Beach Resort",
                    "İnebolu Gardenya Hotel",
                    "İnsula Resort & Spa",
                    "İris Hotel",
                    "İsfanbul Holiday Home & Suites",
                    "İsmira Hotel",
                    "İstanbul Golden City Hotel",
                    "İstanbul Gönen Hotel",
                    "İzmir Palas Hotel",
                    "Jasmin Elite Residence",
                    "Jiva Beach Resort",
                    "Jiva Beach Resort",
                    "Jura Hotels Afyon Thermal",
                    "Justiniano Club Alanya",
                    "Justiniano Deluxe Resort",
                    "Justiniano Park Conti",
                    "Kairaba Alaçatı Beach Resort",
                    "Kairaba Blue Dreams Resort & Spa",
                    "Kalamar Hotel",
                    "Kalevera Hotel",
                    "Kalif Hotel",
                    "Kalinda Inn Otel",
                    "Kalyon Hotel",
                    "Kapadokya Hill Hotel & Spa",
                    "Kapadokya Lodge",
                    "Karaca Otel",
                    "Karaman Kent Hotel",
                    "Karbelsun Hotel",
                    "Karinna Hotel Convention & Spa",
                    "Karmir Resort & Spa",
                    "Karpalas City Hotel & Spa",
                    "Kartal Otel",
                    "Katre Hotel",
                    "Katre Otel",
                    "Kaunos Hotel Köyceğiz",
                    "Kaya İzmir Thermal & Convention",
                    "Kaya Palazzo Golf Resort",
                    "Kaya Palazzo Resort & Residences Le Chic Bodrum",
                    "Kaya Palazzo Ski & Mountain Resort",
                    "Kaya Prestige",
                    "Kaya Uludağ",
                    "Kayı Snow Otel",
                    "Kayseri Köşk Otel",
                    "Kazdağları İda Natura Bungalow Otel",
                    "Kekik Alaçatı Otel Hacımemiş",
                    "Kekik Alaçatı Otel Köyiçi",
                    "Kekik Alaçatı Otel Mayko",
                    "Keleşler Park Otel",
                    "Kemerlihan Deluxe Hotel",
                    "Kempinski Barbaros Bay Bodrum",
                    "Kent Hotel Bursa",
                    "Kerme Ottoman Palace",
                    "Keten Suites Taksim",
                    "Ketenci Hotel",
                    "Kevser Inn Hotel",
                    "Key Hotel",
                    "Kırçuval Hotel",
                    "Kilikya Hotel",
                    "Kilim Otel İzmir",
                    "Kimeros Park Holiday Village",
                    "Kirman Arycanda Deluxe",
                    "Kirman Belazur Resort & Spa",
                    "Kirman Leodikya Resort & Spa",
                    "Kirman Sidemarin Beach & Spa",
                    "Kirman Sidera Luxury & Spa",
                    "Kitapevi Otel",
                    "Kleopatra Royal Palm Hotel",
                    "Kolin Otel",
                    "Konak Hotel",
                    "Konak Park Hotel",
                    "Konaks Otel",
                    "Kordon Otel Alsancak",
                    "Kordon Otel Çankaya",
                    "Korel Thermal Resort Clinic & Spa",
                    "Koru Hotel Bolu",
                    "Koru Hotel Bolu",
                    "Kubaliç Hotel",
                    "Kule Hotel",
                    "Kuştur Club Holiday Village",
                    "Kuum Hotel & Spa",
                    "Kuzucular Park Hotel",
                    "La Boutique Antalya",
                    "La Kumsal Hotel",
                    "La Quinta By Wyndham",
                    "La Quinta by Wyndham Bodrum",
                    "La Vida Blanca",
                    "Labranda Alantur Resort",
                    "Labranda Mares Marmaris",
                    "Labranda TMT Bodrum Resort",
                    "Ladin Otel",
                    "Lalila Blue Suites",
                    "Lambada Otel",
                    "Lamec Hotel Business",
                    "Laodikya Otel",
                    "Lara Hotel",
                    "Lara World Hotel",
                    "Lara World Hotel",
                    "Laren Family Hotel & Spa",
                    "Laren Seaside Hotel & Spa",
                    "Laren Seaside Hotel & Spa",
                    "Larissa Akman Park Hotel",
                    "Larissa Sultan’s Beach Hotel",
                    "Latanya Palm Hotel",
                    "Lavin Otel",
                    "Lazzoni Hotel",
                    "Le Blue Hotel",
                    "Le Meridien Bodrum Beach Resort",
                    "Le Meridien İstanbul Etiler",
                    "Leman Hotel",
                    "Liberty Hotels Ölüdeniz",
                    "Lidya Sardes Thermal & Spa Hotel",
                    "Limak Ambassadore Boutique Hotel",
                    "Limak Arcadia Golf & Sport Resort",
                    "Limak Atlantis De Luxe Hotel & Resort",
                    "Limak Eurasia Luxury Hotel",
                    "Limak Lara De Luxe Hotel & Resort",
                    "Limak Limra Hotel & Resort",
                    "Limak Thermal Boutique Hotel",
                    "Linda Expo Palace",
                    "Lion Park Suites & Residence",
                    "Liona Hotel",
                    "Lionel Hotel İstanbul",
                    "Liparis Resort Hotel & Spa",
                    "Liv Suit Hotel",
                    "Longosphere Glamping",
                    "Lova Hotel & Spa Yalova",
                    "Lugal a Luxury Collection Hotel Ankara",
                    "Lujo Bodrum",
                    "Luxor Garden Hotel",
                    "Lycus River Thermal & Spa Hotel",
                    "M Galery By Sofitel The Galata İstanbul",
                    "Madame Tadia Otel",
                    "Magna Pivot Hotel",
                    "Magna Pivot Hotel",
                    "Maira Deluxe Resort",
                    "Majeste Hotel",
                    "Malabadi Hotel",
                    "Maltepe Otel 2000",
                    "Manastır Otel & Suit",
                    "Mandarin Oriental Bodrum",
                    "Marathon Hotel",
                    "Mardin Airport Hotel",
                    "Margi Otel",
                    "Marina Boutique Fethiye Nidya Hotel",
                    "Marina Hotel & Suites",
                    "Marina Vista Hotel Bodrum",
                    "Marla Hotel",
                    "Marma Hotel İstanbul Asia",
                    "Marmaris Bay Resort By Mp Hotels",
                    "Marpessa Blue Beach Hotel",
                    "Marriott Hotel İstanbul Şişli",
                    "Martı Beach Hotel",
                    "May Thermal Resort & SPA",
                    "Melas Lara Hotel",
                    "Melas Resort Hotel",
                    "Melas Tatil Köyü",
                    "Meleklerevi Cave Hotel",
                    "Mell Hotel Trabzon",
                    "Mercia Hotels & Resorts",
                    "Mercure İstanbul Altunizade",
                    "Mercure İstanbul Bomonti",
                    "Mercure İstanbul Sirkeci",
                    "Mercure İstanbul Ümraniye Hotel",
                    "Mersin HiltonSA",
                    "Mersin HiltonSA",
                    "Mersin Hotel",
                    "Mesopotamia Garden Hotel",
                    "Met Gold Hotel",
                    "Metropolitan Hotels Ankara",
                    "Metropolitan Hotels Bosphorus",
                    "Mets Boutique Hotel",
                    "Mia City Hotel",
                    "Mia Resort Pinepark Holiday Club",
                    "Midas Hotel",
                    "Midmar Hotel",
                    "Milashan Otel",
                    "Miracle İstanbul Asia Hotel",
                    "Mirada Del Lago Otel",
                    "Mirada Del Monte Otel",
                    "Mirage Park Resort",
                    "Mirage World",
                    "Miramare Beach Hotel",
                    "Miras Otel",
                    "Mirel Hotel",
                    "Miroğlu Hotel",
                    "Mitannia Regency Hotel",
                    "Mivara Luxury Resort & Spa",
                    "Modern Life Hotel Bodrum",
                    "Modernity Hotel",
                    "Mola Cunda Hotel",
                    "Monna Roza Beach Resort Hotel",
                    "Monna Roza Garden Resort Hotel",
                    "Montana Pine Resort",
                    "Montania Special Class Hotel",
                    "Montania Town Hotel Mudanya",
                    "Monte Carlo Hotel",
                    "Moonshine Hotel Suites",
                    "Morrian Hotel & Spa",
                    "Mövenpick Hotel Ankara",
                    "Mövenpick Hotel İstanbul Golden Horn",
                    "Mövenpick Hotel İzmir",
                    "Mövenpick Malatya Hotel",
                    "MRG Hotel",
                    "Museum Hotel Cappadocia Unique",
                    "Musho Otel",
                    "Musho Otel",
                    "Nagi Beach Hotel",
                    "Narcia Resort Side",
                    "Nashira Resort Hotel & Aqua Spa",
                    "Navona Otel",
                    "Naz City Hotel",
                    "Nazar Otel",
                    "Nearport Hotel",
                    "Neba Royal Hotel",
                    "Neva Palas",
                    "Nevada Hotel & Spa",
                    "Nevali Otel",
                    "New Garden Hotel",
                    "New Karaman Hotel",
                    "New Park Ankara",
                    "Newway Hotel",
                    "NG Afyon",
                    "Ng Enjoy",
                    "NG Sapanca Wellness & Convention",
                    "Nidya Hotel Galataport",
                    "Nidya Otel Esenyurt",
                    "Ninova Thermal Spa & Hotel",
                    "Niss Lara Hotel",
                    "Nizapark Otel Ankara",
                    "Nobel Oteli",
                    "North Point Otel Denizli",
                    "Northdoor Hotel",
                    "Notte Boutique Hotel",
                    "Nova Beach Hotel",
                    "Nova Park Hotel",
                    "Novotel Diyarbakır",
                    "Novotel Gaziantep",
                    "Novotel İstanbul Bosphorus Karaköy",
                    "Novotel İstanbul Zeytinburnu",
                    "Novotel Kayseri",
                    "Novotel Konya",
                    "Novotel Trabzon",
                    "Nox Suite",
                    "Nysa Otel",
                    "Obam Termal Resort Otel&Spa",
                    "Ocean Blue High Class Hotel",
                    "Odyssey Residence Suite Hotel",
                    "Okaliptüs Hotel Bitez",
                    "Olbia Hotel",
                    "Olbios Marina Resort Hotel",
                    "Olira Boutique Hotel & Spa",
                    "Ommer Hotel",
                    "On Oda Alaçatı",
                    "On7 Hotel",
                    "Onhann Hotel",
                    "On'Live Hotel",
                    "Opera Hotel Bosphorus",
                    "Orange County Resort Hotel Alanya",
                    "Orange County Resort Hotel Belek",
                    "Orange County Resort Hotel Kemer",
                    "Orcey Hotel",
                    "Orion Beach Hotel",
                    "Orty Airport Hotel",
                    "Oruçoğlu Oreko Otel",
                    "Oruçoğlu Termal Resort Afyon",
                    "Otel Ahsaray",
                    "Otel Akçakoca",
                    "Otel Akçakoca",
                    "Otel Yelkenkaya",
                    "Ottopera Hotel",
                    "Oylat Kaplıcaları Aşiyan Otel",
                    "Oylat Kaplıcaları Çağlayan Otel",
                    "Oytun Park Hotel",
                    "Ölüdeniz Blu Luxury Boutique Hotel",
                    "Ömer Holiday Resort",
                    "Ömer Thermal Hotel & Holiday Village",
                    "Ömür Otel",
                    "Örsmaris Boutique Hotel",
                    "Özgür Bey Spa Hotel",
                    "Özkaymak Otel",
                    "Özpark Hotel",
                    "Pacco Boutique Hotel",
                    "Pacco Sea City Hotel Spa",
                    "Pacco Sea City Hotel Spa",
                    "Palan Otel",
                    "Palm City Hotel Akhisar",
                    "Palm City Hotel Turgutlu",
                    "Palm Wings Ephesus Beach Resort",
                    "Paloma Finesse",
                    "Pam Thermal Hotel",
                    "Panorama Plaza Hotel",
                    "Papillon Ayscha",
                    "Papillon Belvil Hotel",
                    "Papillon Zeugma Relaxury",
                    "Paradise Island Hotel Bayramoğlu",
                    "Parion Hotel",
                    "Park Dedeman Denizli",
                    "Park Dedeman Eskişehir",
                    "Park Dedeman Trabzon",
                    "Park Hyatt İstanbul Maçka Palas",
                    "Park Inn By Radisson Ataşehir",
                    "Park Inn By Radisson İzmir",
                    "Park Inn By Radisson Odayeri İstanbul",
                    "Park Inn By Radisson Samsun",
                    "Park Royal Hotel Luxury Adana",
                    "Pasaport Pier Hotel",
                    "Paşa Park Otel",
                    "Patalya Termal Resort Otel",
                    "Patara Prince Hotel",
                    "Peerless Villas Hotel",
                    "Pera Palace Hotel",
                    "Perdikia Hill Fethiye",
                    "Perissia Hotel",
                    "Petra Inn Cappadocia",
                    "Pırıl Hotel Thermal & Beauty Spa",
                    "Pine Beach Resort",
                    "Pink Palace Otel",
                    "Pirate's Beach Club",
                    "Pirate's Beach Club",
                    "Plaza Otel Diyarbakır",
                    "Plus Suit Ataşehir",
                    "Point Hotel Barbaros",
                    "Point Otel Ankara",
                    "Point Otel Taksim",
                    "Polat Renaissance İstanbul Otel",
                    "Porto Bello Hotel Resort & Spa",
                    "Premier Inn Sakarya",
                    "Premier Nergis Beach Hotel",
                    "Premier Solto Hotel By Corendon",
                    "Prestige Hotel Diyarbakır",
                    "Prestige Hotel Dönmez",
                    "Prestige Thermal Hotel Spa&Wellness",
                    "Privado Hotels",
                    "Puding Marina Residence",
                    "Pullman İstanbul Hotel & Convention Center",
                    "Pure Blanche Hotel",
                    "Queen's Park Göynük",
                    "Queen's Park Le Jardin Resort & Spa",
                    "Rabat Resort Hotel",
                    "Radisson Blu Bosphorus Hotel Ortaköy",
                    "Radisson Blu Hotel Diyarbakır",
                    "Radisson Blu Hotel İstanbul Pera",
                    "Radisson Blu Hotel Kayseri",
                    "Radisson Blu Hotel Trabzon",
                    "Radisson Blu Hotel Vadi İstanbul",
                    "Radisson Blu Ordu",
                    "Radisson Blu Resort & Spa Çeşme",
                    "Radisson Blu Resort & Spa Tuzla",
                    "Raffles İstanbul Otel",
                    "Ramada By Wyndham Bursa Çekirge Termal & Spa",
                    "Ramada By Wyndham Diyarbakır",
                    "Ramada By Wyndham Elazığ",
                    "Ramada by Wyndham Isparta",
                    "Ramada by Wyndham Istanbul Alibeykoy",
                    "Ramada by Wyndham Istanbul Asia",
                    "Ramada By Wyndham İskenderun Harbour",
                    "Ramada by Wyndham İstanbul Taksim",
                    "Ramada by Wyndham Mersin",
                    "Ramada By Wyndham Niğde",
                    "Ramada By Wyndham Sakarya",
                    "Ramada by Wyndham Soma",
                    "Ramada By Wyndham Tire",
                    "Ramada By Wyndham Uşak",
                    "Ramada By Wyndham Van",
                    "Ramada by Wyndham Yalova",
                    "Ramada Encore by Wyndham Eskisehir",
                    "Ramada Encore by Wyndham Istanbul Kartal",
                    "Ramada Encore By Wyndham İstanbul Basın Express",
                    "Ramada Encore by Wyndham İstanbul Bayrampaşa",
                    "Ramada Encore İzmir",
                    "Ramada Gemlik",
                    "Ramada Gümüşhane",
                    "Ramada Hotel & Suites by Wyndham Adana",
                    "Ramada Hotel & Suites by Wyndham Kemalpaşa İzmir",
                    "Ramada Hotel & Suites by Wyndham Kuşadası",
                    "Ramada Hotel Suites Edirne",
                    "Ramada Plaza Antalya",
                    "Ramada Plaza Antalya",
                    "Ramada Plaza By Wyndham Istanbul City Center",
                    "Ramada Plaza By Wyndham İstanbul Tekstilkent",
                    "Ramada Plaza By Wyndham Kahramanmaraş",
                    "Ramada Plaza By Wyndham Konya",
                    "Ramada Plaza by Wyndham Malatya Altın Kayısı",
                    "Ramada Plaza by Wyndham Mardin",
                    "Ramada Plaza by Wyndham Rize",
                    "Ramada Plaza İzmit",
                    "Ramada Resort Bodrum",
                    "Ramada Resort Kazdağları Thermal & Spa",
                    "Ramada Tekirdağ",
                    "Ravanda Hotel",
                    "Rawda Resort Hotels Altınoluk",
                    "Raymar Resort & Aqua",
                    "Real Konak Hotel",
                    "Reges a Luxury Collection Resort & Spa",
                    "Regnum Carya",
                    "Remer Hotel",
                    "Renaissance İzmir Hotel",
                    "Rhiss Hotel Bostancı",
                    "Rıdvan Otel Çeşme",
                    "Richmond Ephesus Resort",
                    "Richmond Nua Wellness Spa Sapanca",
                    "Ridos Thermal Hotel & Spa",
                    "Rios Beach Hotel",
                    "Rios Beach Hotel",
                    "Risus Aqua Beach Resort Hotel",
                    "Riva Reşatbey Boutique & Business Hotel",
                    "Rixos Downtown Antalya",
                    "Rixos Hotel Beldibi",
                    "Rixos Pera",
                    "Rixos Premium Belek",
                    "Rixos Premium Bodrum",
                    "Rixos Premium Göcek",
                    "Rixos Premium Tekirova",
                    "Rixos Sungate",
                    "Robinson Club Nobilis",
                    "Rodinn Park Hotel",
                    "Rodosto Hotel",
                    "Rosy Hotel",
                    "Royal Anka Hotel",
                    "Royal Arena Resort&Spa",
                    "Royal Asarlık Beach Hotel & Spa",
                    "Royal Bilgiç Hotel",
                    "Royal Carine Otel Ankara",
                    "Royal Comfort Hotel",
                    "Royal Dragon Hotel",
                    "Royal Garden Select Suite",
                    "Royal Holiday Palace Hotel",
                    "Royal Hotel İnegöl",
                    "Royal Palace Kuşadası Hotel",
                    "Royal Seginus Hotel",
                    "RuinAdalia Hotel",
                    "RYS Hotel",
                    "Safa Sorgun Termal Otel",
                    "Saffron Hotel Kahramanmaraş",
                    "Safran City Hotel & Spa",
                    "Safran Thermal Resort Hotel Spa & Convention Center",
                    "Sahil Martı",
                    "Sailors Beach Club Hotel",
                    "Sakarya Ottoman Hotel",
                    "Saklı Konak Cappadocia",
                    "Salbakos Herakleia Boutique Hotel",
                    "Salmakis Otel Bodrum",
                    "Sam My House Hotel",
                    "Sandal Otel",
                    "Sandıklı Thermal Park Hotel",
                    "Santa Marina Hotel",
                    "Saphir Hotel",
                    "Saphir Resort & Spa",
                    "Sapran Deluxe Hotel",
                    "Sarar Otel Kızılcıklı",
                    "Sarıkamış Kayı Resort Otel",
                    "Sarot Thermal Park Resort & Spa",
                    "Savona Otel",
                    "Sea Bird Hotel",
                    "Sea Life Buket Beach & Resort",
                    "Sea Life Family Resort",
                    "Sea Palm Otel Yalıkavak",
                    "Sea Planet Resort & Spa",
                    "Sealife Lounge",
                    "Sealife Lounge",
                    "Seandos Otel",
                    "Seaport Otel",
                    "Seçkin Hotel SPA&Wellness",
                    "Sedef Otel",
                    "Seher Resort & Spa",
                    "Seher Sun Palace Resort & Spa",
                    "Selçuklu Otel Ermenek",
                    "Selge Beach Resort & Spa",
                    "Sen Otel",
                    "Senses Hotel",
                    "Senza Grand Santana Hotel",
                    "Senza The Inn Resort & Spa",
                    "Sera Lake Resort Hotel",
                    "Sergah Otel",
                    "Serra Otel",
                    "Sertil Deluxe Hotel",
                    "Sesin Hotel Marmaris",
                    "Seven Deep Hotel",
                    "Seven Seas Hotel Blue",
                    "Seven Seas Hotel Life",
                    "Seyhan Hotel",
                    "Sheraton Bursa Hotel",
                    "Sheraton Bursa Hotel",
                    "Sheraton City Center Hotel",
                    "Sheraton Çeşme Hotel Resort & Spa",
                    "Sheraton Grand Adana Hotel",
                    "Sheraton Grand Samsun Hotel",
                    "Sheraton Hotel & Convention Center Ankara",
                    "Sheraton İstanbul Ataköy Hotel",
                    "Sheraton İstanbul Ataşehir",
                    "Shimall Deluxe Hotel",
                    "Shimall Hotel ve Kongre Merkezi",
                    "Side Alegria Hotel",
                    "Side Crown Charm Hotel",
                    "Side Crown Sunshine",
                    "Side Crowne Palace",
                    "Side Premium",
                    "Side Prenses Hotel",
                    "Side Royal Palace",
                    "Side Sungate Hotel & SPA",
                    "Simav Belediyesi Eynal Kaplıcaları İşletmesi",
                    "Simena Hotel",
                    "Sirene Davras Hotel",
                    "Sirius Deluxe Hotel",
                    "Sisus Otel Çeşme",
                    "Sivas Büyük Hotel",
                    "Sivas Köşk Otel",
                    "Six Senses Kocataş Mansions İstanbul",
                    "Solmaz Hotel",
                    "Somerset Maslak İstanbul",
                    "Sonnen Hotel",
                    "Soylu Otel",
                    "Soylu Otel",
                    "Suadiye Hotel",
                    "Sueno Hotels Beach",
                    "Sueno Hotels Deluxe Belek",
                    "Sueno Hotels Golf Belek",
                    "Suhan Kapadokya Otel & Spa",
                    "Sui Resort Hotel",
                    "Suite Laguna Hotel",
                    "Sular Hotel",
                    "Sultan Otel Sivas",
                    "Suncity Hotel & Beach Club",
                    "Sunday Beach Hotel",
                    "Sundia By Liberty Exclusive Fethiye",
                    "Sundia By Liberty Fethiye",
                    "Sundia By Liberty Ölüdeniz",
                    "Sunprime Alanya Beach Hotel",
                    "Sunprime C-lounge Hotel",
                    "Sunset Marmaris Boutique Hotel",
                    "Susesi Luxury Resort",
                    "Susona Bodrum LXR Hotels & Resorts",
                    "Süral Hotel",
                    "Süral Resort Hotel",
                    "Süral Saray Hotel",
                    "SV Business Otel Diyarbakır",
                    "Svalinn Hotel",
                    "Swandor Topkapı Palace",
                    "Sway Hotels Palandöken Erzurum",
                    "Swissotel Ankara",
                    "Swissotel Büyük Efes İzmir",
                    "Swissotel İstanbul The Bosphorus",
                    "Swissotel Resort Bodrum Beach",
                    "Symbola Ölüdeniz Beach Hotel",
                    "Şapçı Prestige Hotel",
                    "Şifne Termal Otel",
                    "Şiir Butik Otel",
                    "Şirehan Otel",
                    "Şirin Park Otel",
                    "Tafoni Cave Hotel",
                    "Taksim Square Hotel",
                    "Tasigo Hotels Eskişehir Bademlik Termal",
                    "Taşar Royal Hotel",
                    "Taşhan Otel",
                    "Tav Airport Hotel İzmir",
                    "Tekirdağ Yat Hotel",
                    "Telmessos Select Hotel",
                    "Temple Miletos & Spa Hotel",
                    "Tempo Suites Airport",
                    "Teymur Continental Hotel",
                    "The Ancient Mesopotamia Hotel",
                    "The Ankara Hotel",
                    "The Black Eskişehir",
                    "The Bodrum EDITION",
                    "The Bostancı Hotel",
                    "The Corner Park Hotel",
                    "The Crater Hotel",
                    "The Elysium İstanbul",
                    "The Fortyfive Business Hotel & Spa",
                    "The Green Park Gaziantep",
                    "The Green Park Hotel Ankara",
                    "The Green Park Hotel Merter",
                    "The Green Park Hotel Taksim",
                    "The Green Park Hotels & Resort Kartepe",
                    "The Green Park Pendik Hotel & Convention Center",
                    "The House Hotel Vault Karaköy",
                    "The Kars Park Hotel",
                    "The Kayseri Loft Otel",
                    "The Land of Legends Kingdom Otel",
                    "The Lumos Deluxe",
                    "The Marmara Antalya",
                    "The Marmara Bodrum",
                    "The Marmara Şişli",
                    "The Marmara Taksim",
                    "The Merlot Hotel",
                    "The Ness Thermal Hotel Spa & Convention Center",
                    "The Nowness Luxury Hotel & Spa",
                    "The Place İstanbul",
                    "The Room Hotel Apartments",
                    "The Sign Esentepe Hotel & Ski Center",
                    "The St Regis İstanbul",
                    "The Wyspy Hotel",
                    "Thermemaris Thermal & Spa Hotel",
                    "Throne Beach Resort & Spa",
                    "Throne Seagate Belek Hotel",
                    "Tiara Termal & Spa Hotel",
                    "Tilmen Hotel",
                    "Tilya Resort Hotel",
                    "Titan Select Hotel",
                    "Titanic Business Hotel Kartal",
                    "Tourist Hotel Kapadokya",
                    "Trendy Aspendos Beach",
                    "Trendy Lara",
                    "Trendy Verbena Beach",
                    "Trio Suites Hotel",
                    "Troia Tusan Hotel",
                    "Tuğcan Hotel",
                    "Tuğcu Hotel Select",
                    "Tui Blue Ephesus Otel & Aqua Fantasy Aqua Park Tatil Köyü",
                    "Tuna Hotel",
                    "Turkish Cave House",
                    "Türkbükü Hill Hotel & Beach",
                    "Tüyap Palas Hotel",
                    "Tzob Akman Otel",
                    "Uçhisar Kaya Otel",
                    "Ulu Resort Hotel",
                    "Uranus İstanbul Topkapı Hotel",
                    "Usta Park Hotel",
                    "Utopia World Hotel",
                    "Ünlüselek Hotel",
                    "Venezia Palace Deluxe Resort",
                    "Venosa Beach Resort Spa",
                    "Venüs Termal Butik Otel",
                    "Verde Hotel",
                    "Veyron Hotels",
                    "Victoria Suite Otel & Spa",
                    "Viento Hotel Alaçatı",
                    "Viking Nona Beach Hotel",
                    "Viking Park Otel",
                    "Viking Star Hotel",
                    "Viking Suite Hotel",
                    "Villa Rustica Hotel",
                    "Villa Side Residence",
                    "Vista Boutique Hotel",
                    "Vita Bella Resort Hotel & Spa",
                    "Vogue Hotel Supreme Bodrum",
                    "VONResort Abant",
                    "VONResort Elite",
                    "VONResort Golden Beach Hotel",
                    "VONResort Golden Coast Hotel",
                    "W Hotel İstanbul",
                    "Wellborn Luxury Hotel",
                    "Wes Hotel",
                    "White Star Hotel",
                    "Wind of Lara Hotel & SPA",
                    "Wish More Hotel İstanbul",
                    "Wome Deluxe Hotel",
                    "Wonasis Resort & Aqua Hotel",
                    "Workinn Hotel",
                    "WOW İstanbul Hotel 5*",
                    "Woxxie Hotel Akyarlar",
                    "Wyndham Ankara",
                    "Wyndham Çerkezköy",
                    "Wyndham Grand İstanbul Europe",
                    "Wyndham Grand İstanbul Kalamış Marina",
                    "Wyndham Grand İstanbul Levent",
                    "Wyndham Grand İzmir Özdilek",
                    "Wyndham Grand Kayseri",
                    "Xanadu Island",
                    "Xanadu Resort Hotel",
                    "Xperia Grand Bali Hotel",
                    "Xperia Saray Beach Hotel",
                    "Yacht Classic Hotel",
                    "Yalçın Hotel Resort",
                    "Yasmin Resort Bodrum",
                    "Yay Grand Otel",
                    "Yelken Mandalinci Spa & Wellness Hotel",
                    "Yeniçeri City Hotel",
                    "Yılmazoğlu Park Otel",
                    "Yol İş Holiday Adana",
                    "Yol İş Holiday Otel Trabzon",
                    "Yunak Evleri",
                    "Yunus Hotel Marmaris",
                    "Yusuf Yiğitoğlu Konağı",
                    "Yücel Otel",
                    "Zalifre Otel",
                    "Zeniva Hotel",
                    "Zeyn Hotel",
                    "Zeynep Hotel",
                    "Zeytin Arası Apart Otel",
                    "Zeytinada Otel",
                    "Zigana Resort Alaçatı",
                    "Zorlu Grand Hotel Trabzon",
                    "Calidus Hotel",
                    "Hotel Benan",
                    "Acem Hotel",
                    "Narven Termal Kasaba",
                    "Akay Garden Family Club",
                    "İskelem Otel",
                    "Doora Bodrum Hotel",
                    "Palm Wings Beach Resort & Spa Kuşadası",
                    "Euphoria Tekirova Hotel",
                    "Champion Holiday Village",
                    "Yel Holiday Resort",
                    "Elementa Boutique Hotel",
                    "Trend Life Hotels",
                    "Oksijen Zone Hotels Uludağ",
                    "Polat Erzurum Resort Hotel",]

                css = '<style>\
                .ed_'+ config.scenarioname + '_tooltip{ position: absolute; width: 250px; left: -215%; margin-top: -90px; border-radius: 6px; padding: 4px 5px; background-color: #555!important; z-index: 999999; display: none;}\
                .ed_'+ config.scenarioname + '_tooltip_inner{text-align: center; font-size:12px; font-family: -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol"!important;color: #c4c4c4!important }\
                .ed_'+ config.scenarioname + '_tooltip_inner .rule{padding:2px;}\
                .arrow-right{width: 0; height: 0; border-top: 10px solid transparent; border-bottom: 10px solid transparent; border-left: 10px solid #555!important; position: absolute; left: 39%; margin-top: -67px; display: none; transform: rotate(90deg); -webkit-transform: rotate(90deg);}\
                </style>'
                jQuery('head').append(css)




                jQuery(document).ajaxComplete(function (r, s, p) {
                    console.log('ajax done')
                    if (p.url.indexOf("o") > -1) {
                        console.log('first if')
                        var count = jQuery('.booking-item.booking-filter-item').length;
                        console.log(count)
                        var i;
                        for (i = 0; i < count; i++) {
                            if (CoronaList.includes(jQuery('.booking-item.booking-filter-item:eq(' + i + ') .hotellist-item-info-mobile .hotellist-hotel-name').text().trim())) {
                                console.log('second if')
                                if (jQuery('.booking-item.booking-filter-item:eq(' + i + ') .hotellist-item-info-mobile .hotellist-hotel-name .ed-BadgeTourism').length === 0) {
                                    jQuery('.booking-item.booking-filter-item:eq(' + i + ') .hotellist-item-info-mobile .hotellist-hotel-name').append('<div class="ed-BadgeTourism" style=" position: relative; margin: 0px 0px -20px 0px; width: 45px; float: right;"><img src="https://cdn.8digits.com/f/u/s2adg7rq/94373319-3e98-4d51-b4e2-b881f3f26677.png"></div>')
                                }
                            }
                        }

                    }
                });

            },
            control: function () {
            },
            init: function () {
                if (main.factory.prototype.control() == false) {
                    return false
                }
                var _exec = main.factory.prototype.random();
                if (!_exec) {
                    EightDigits.analytics.sendEvent(config.analytics, "NotShown");
                    return false;
                }
                main.factory.prototype.start();
            }
        };

        boot = function () {
            return main.factory.prototype.init();
        };

        boot();

    };
    var _ed_otelTourismSertifikaListingM = new EightDigits.sf();
    _ed_otelTourismSertifikaListingM.otelTourismSertifikaListingM();
})();
